# a = input()
# print(type(a))
# a = int(input())
# print(type(a))
# a = float(input())
# print(type(a))
print("_____________________________________________________")
# a = int(input())
# b = int(input())
# print(a * b)
# a,b = input("Please enter two integers: ").split()
# a=int(a)
# b = int(b)
# print(a * b)
print("_____________________________________________________")
# name, family, age, average = input("Please enter your first name, last name, age and gdp (out of 20) ").split()
# age = int(age)
# average = float(average)
# print(average + 1)
print("_____________________________________________________")
a, b = map(int, input("Please enter two integers only integers: ").split())
print(a +b)
# زمانی از map استفاده می‌کنیم که همه‌ی ورودی‌ها از یک جنس باشند
